### ISSUE TITLE
Won't run on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by youradds** [jorgebastida/glue#222]
I just came across this tool, and it looks awesome! I'm having some fun getting it going though. 

I've just installed on my Ubuntu 16.0.4 server, using:

`apt-get install glue-sprite`

I didn't get any errors with the install. However, when I try and run it I do:

> glue-sprite icons sprites
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (Jinja2 2.8 (/usr/lib/python3/dist-packages), Requirement.parse('Jinja2<2.8,>=2.7'), {'glue'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/glue-sprite", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'Jinja2<2.8,>=2.7' distribution was not found and is required by glue

Any suggestions? 

```
sudo dpkg -l | grep jinj
ii  python3-jinja2                    2.8-1                               all          small but fast and easy to use stand-alone template engine

```

**Comment by youradds** [comment]
FWIW, I found out that I'm running an older (0.11.1) version of glue. It seems the current version is 0.13. How do I go about upgrading my install? 

I'm not great with Python, so have never done this before (most stuff gets done via apt-get)

Thanks
