### ISSUE TITLE
'module' object has no attribute 'VERSION'

### ISSUE THREAD

**Issue by lukesomnus** [jorgebastida/glue#230]
Version: 0.13
Python: 2.7.16 (default, Mar  4 2019, 09:01:38)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
Traceback (most recent call last):
  File "/usr/local/bin/glue", line 11, in <module>
    load_entry_point('glue==0.13', 'console_scripts', 'glue')()
  File "/usr/local/lib/python2.7/site-packages/glue/bin.py", line 262, in main
    sys.stderr.write("PIL version: {0}\n".format(PImage.VERSION))
AttributeError: 'module' object has no attribute 'VERSION'

**Comment by lukesomnus** [comment]
when the filename of the source image is Chinese, it will show error info above.
